"""Create_dimension_default_scores_table

Revision ID: 1ef8b945b1f6
Revises: 249cc67cc8b8
Create Date: 2025-08-07 22:17:52.548214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef8b945b1f6'
down_revision = '249cc67cc8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_record')
    op.drop_table('evaluation_score')
    op.drop_table('evaluation_dimension')
    op.drop_table('evaluation_task')
    op.drop_table('employee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), server_default=sa.text("'pbkdf2:sha256:150000$abc123$def456'"), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('employee_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_frozen', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'员工'"), nullable=False),
    sa.Column('position_coefficient', sa.FLOAT(), server_default=sa.text('(1.0)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('quarter', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default="published", nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_dimension',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default="active", nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_score',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('record_id', sa.INTEGER(), nullable=False),
    sa.Column('dimension_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dimension_id'], ['evaluation_dimension.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['evaluation_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('evaluator_id', sa.INTEGER(), nullable=False),
    sa.Column('evaluatee_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('withdrawal_reason', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['evaluatee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
