"""Create rollback migration

Revision ID: a5607848e28e
Revises: 1ef8b945b1f6
Create Date: 2025-08-07 22:24:57.199471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5607848e28e'
down_revision = '1ef8b945b1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('position', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), server_default=sa.text("'pbkdf2:sha256:150000$abc123$def456'"), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('employee_id', sa.VARCHAR(length=20), nullable=True),
    sa.Column('is_frozen', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'员工'"), nullable=False),
    sa.Column('position_coefficient', sa.FLOAT(), server_default=sa.text('(1.0)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
